---

- name: Ensure pandora path allowed for libreoffice
  ansible.builtin.lineinfile:
    path: /etc/apparmor.d/usr.lib.libreoffice.program.soffice.bin
    line: '  owner @{HOME}/pandora/tasks/** rwk,'
    insertafter: '^profile libreoffice-soffice /usr/lib/libreoffice/program/soffice.bin .*{'
    mode: '0644'
    backup: "{{ pandora_backup }}"
  notify:
    - Refresh apparmor libreoffice

# https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg6063132.html
# https://gitlab.com/apparmor/apparmor/-/merge_requests/1236
- name: Workaround apparmor runbindable
  ansible.builtin.replace:
    path: /etc/apparmor.d/abstractions/passt
    regexp: '^  mount options=\(rw, runbindable\) \/,'
    replace: '  mount options=(rw, runbindable) -> /,'
    mode: '0644'
    backup: "{{ pandora_backup }}"
  notify:
    - Refresh apparmor libreoffice
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 24
