---

- name: Source kvrocks dependencies
  ansible.builtin.apt:
    name:
      - gcc
      - g++
      - make
      - libsnappy-dev
      - autoconf
      - automake
      - libtool
      - googletest
      - libgtest-dev
      - git
      - cmake
      - python3
      - libssl-dev
    state: present
  become: yes
  become_user: root

- name: Clone kvrocks repository
  ansible.builtin.git:
    repo: https://github.com/apache/kvrocks.git
    dest: "{{ pandora_home }}/kvrocks"
    version: "{{ pandora_kvrocks_version }}"
    update: yes
  become: yes
  become_user: "{{ pandora_user }}"

- name: Build kvrocks
  ansible.builtin.command:
    cmd: ./x.py build -DENABLE_OPENSSL=ON
  args:
    chdir: "{{ pandora_home }}/kvrocks"
    creates: "{{ pandora_home }}/kvrocks/build/kvrocks"
  become: yes
  become_user: "{{ pandora_user }}"
