---

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Set fact is_container
  ansible.builtin.set_fact:
    is_container: true
  when: >
    (ansible_virtualization_type is defined and
      (ansible_virtualization_type == "docker"
       or ansible_virtualization_type == "containerd"
       or ansible_virtualization_type == "container"
      )
    )

- name: Ensure archives folder exists
  ansible.builtin.file:
    dest: "{{ install_archives }}"
    state: directory
    mode: '0775'
  become: yes
  become_user: root

- name: Debian | Update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: "{{ pandora_apt_cache_valid_time | default('3600') }}"
  become: yes
  become_user: root
  when: ansible_os_family == 'Debian'

- name: Ensure dependencies packages are present
  ansible.builtin.package:
    name: "{{ pandora_pkgs }}"
    state: present
  become: yes
  become_user: root
  register: pkg_result
  until: pkg_result is success
  notify:
    - Updating ClamAV Signatures

- name: Ensure / mounted with flag acl for ansible become unprivileged user
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state }}"
  loop: "{{ pandora_fstab }}"
  become: yes
  become_user: root
  when:
    - not is_container

- name: Ensure pandora user exists
  ansible.builtin.user:
    name: "{{ pandora_user }}"
    home: "{{ pandora_home }}"
    system: true
  become: yes
  become_user: root

- name: Ensure right permissions for pandora home
  ansible.builtin.file:
    path: "{{ pandora_home }}"
    owner: "{{ pandora_user }}"
    mode: '0755'
    state: directory
  become: yes
  become_user: root

- name: Grant user poetry access to archives
  ansible.posix.acl:
    path: "{{ install_archives }}"
    entity: "{{ pandora_user }}"
    etype: user
    permissions: rwx
    state: present
  become: yes
  become_user: root

- name: Import poetry
  ansible.builtin.import_tasks: poetry.yml
  vars:
    poetry_user: "{{ pandora_user }}"

- name: Import redis-source
  ansible.builtin.import_tasks: redis-source.yml
- name: Import kvrocks-source
  ansible.builtin.import_tasks: kvrocks-source.yml

- name: Import pandora
  ansible.builtin.import_tasks: pandora.yml
  become: yes
  become_flags: -H
  become_user: "{{ pandora_user }}"

- name: Ensure logrotate is configured
  ansible.builtin.template:
    src: logrotate-pandora.j2
    dest: /etc/logrotate.d/pandora
    mode: '0644'
    owner: root
    backup: "{{ pandora_backup }}"

- name: Import workers
  ansible.builtin.import_tasks: workers.yml
  become: yes
  become_user: "{{ pandora_user }}"

- name: Import av-workers
  ansible.builtin.import_tasks: av-workers.yml
  become: yes
  become_user: root

- name: Import apparmor
  ansible.builtin.import_tasks: apparmor.yml
  become: yes
  become_user: root
  when:
    - pandora_apparmor_enable | bool

- name: Import firewall-ufw
  ansible.builtin.import_tasks: firewall-ufw.yml
  become: yes
  become_user: root
  when:
    - pandora_ufw|bool
    - not is_container

- name: Import systemd
  ansible.builtin.import_tasks: systemd.yml
  become: yes
  become_user: root
  when:
    - not is_container

- name: Check if pandora port is listening
  ansible.builtin.wait_for:
    port: "{{ pandora_listen_port }}"
  when:
    - not is_container | bool
