---

- name: Enable Recent Tasks page availability
  ansible.builtin.blockinfile:
    path: "{{ pandora_root }}/website/web/__init__.py"
    mode: '0644'
    marker: "# ANSIBLE MANAGED BLOCK - recent tasks"
    state: absent
  when: pandora_recent_tasks|bool

- name: Disable Recent Tasks page availability
  ansible.builtin.blockinfile:
    path: "{{ pandora_root }}/website/web/__init__.py"
    mode: '0644'
    insertafter: '^def api_tasks\(\):'
    marker: "# ANSIBLE MANAGED BLOCK - recent tasks"
    block: |
      # ensure correct indent
          return redirect(url_for('api_root'), 302)
    backup: yes
  when: not pandora_recent_tasks|bool
