---

- name: Source redis dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - tcl
    state: present
  become: yes
  become_user: root

- name: Clone valkey repository
  ansible.builtin.git:
    repo: https://github.com/valkey-io/valkey.git
    dest: "{{ pandora_home }}/valkey"
    version: "{{ pandora_valkey_version }}"
  become: yes
  become_user: "{{ pandora_user }}"

- name: Build valkey
  ansible.builtin.command: make
  args:
    chdir: "{{ pandora_home }}/valkey"
    creates: "{{ pandora_home }}/valkey/src/valkey-server"
  become: yes
  become_user: "{{ pandora_user }}"
