---

- name: Source redis dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - tcl
    state: present
  become: yes
  become_user: root

- name: Clone redis repository
  ansible.builtin.git:
    repo: https://github.com/redis/redis.git
    dest: "{{ pandora_home }}/redis"
    version: 6.2
  become: yes
  become_user: "{{ pandora_user }}"

- name: Build redis
  ansible.builtin.command: make
  args:
    chdir: "{{ pandora_home }}/redis"
    creates: "{{ pandora_home }}/redis/src/redis-server"
  become: yes
  become_user: "{{ pandora_user }}"
