---

- name: Ensure systemd is present
  ansible.builtin.package:
    name: systemd
    state: present

- name: Ensure redis does not daemonize
  ansible.builtin.replace:
    dest: "{{ pandora_root }}/cache/cache.conf"
    regexp: "^daemonize .*"
    replace: "daemonize no"
    mode: '0644'
    owner: "{{ pandora_user }}"
    backup: "{{ pandora_backup }}"
  notify:
    - restart pandora-redis

- name: Configure pandora systemd units
  ansible.builtin.template:
    src: "systemd-{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '0644'
  notify:
    - reload systemd
    - "restart {{ item }}"
  loop: "{{ pandora_systemd_units }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start pandora services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ pandora_systemd_units }}"
