---

roles:
  - src: https://github.com/juju4/ansible-kvrocks/
    version: main
    name: juju4.kvrocks
  - src: https://github.com/geerlingguy/ansible-role-redis/
    version: master
    name: geerlingguy.redis
  - src: https://github.com/juju4/ansible-adduser/
    version: main
    name: juju4.adduser
  - src: https://github.com/juju4/ansible-harden/
    version: main
    name: juju4.harden
  - src: https://github.com/juju4/ansible-tinyproxy/
    version: main
    name: juju4.tinyproxy
  - src: https://github.com/juju4/ansible-osquery/
    version: main
    name: juju4.osquery
  - src: https://github.com/juju4/ansible-harden-nginx/
    version: main
    name: juju4.harden_nginx
  - name: geerlingguy.java
