---

roles:
  - src: https://github.com/juju4/ansible-kvrocks/
    version: main
    name: juju4.kvrocks
  - src: https://github.com/geerlingguy/ansible-role-redis/
    version: master
    name: geerlingguy.redis
