---
name: AnsibleCI

on:
  push:
  pull_request:
  schedule:  # run weekly, every Thursday 01:00
    - cron: '40 1 * * 4'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.8]
        molecule_distro:
          - 'ubuntu:22.04'
          - 'ubuntu:20.04'
    env:
      ANSIBLE_CALLBACK_ENABLED: profile_tasks
      MOLECULE_NO_LOG: "false"

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.pandora
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] ansible-lint flake8 testinfra ansible
          mkdir -p $HOME/.ansible/roles && ln -s $GITHUB_WORKSPACE/juju4.pandora $HOME/.ansible/roles/
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/juju4.pandora && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
