---
name: default-bare

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # run weekly, every Thursday 01:00
    - cron: '40 1 * * 4'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-${{ matrix.version }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - distribution: ubuntu
            version: '24.04'
            suite: default
            experimental: false
          - distribution: ubuntu
            version: '22.04'
            suite: default
            experimental: false
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.pandora
      ANSIBLE_SUITE: ${{ matrix.suite }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          set -x
          pwd
          env
          find -ls
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: verify
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/verify.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: On failure
        run: |
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com || true
          ping -c 1 8.8.8.8 || true
          ps axuw
          netstat -anp
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - ansible setup
        run: |
          ansible -i inventory --connection=local -m setup localhost
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - systemd
        run: |
          systemctl -l --no-pager status pandora-imap_fetcher || true
          systemctl -l --no-pager status pandora-kvrocks|| true
          systemctl -l --no-pager status pandora-redis || true
          systemctl -l --no-pager status pandora-unoserver || true
          systemctl -l --no-pager status pandora-web || true
          systemctl -l --no-pager status pandora-workers || true
          systemctl -l --no-pager status clamav-freshclam || true
          systemctl -l --no-pager status clamav-daemon || true
          systemd-analyze --no-pager security || true
          rsyslogd -v
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - files
        run: |
          set -x
          sudo ls -la /var/_pandora/
          sudo ls -la /var/_pandora/kvrocks
          sudo ls -la /var/_pandora/valkey || true
          sudo ls -la /var/_pandora/pandora
          sudo cat /var/_pandora/pandora/config/generic.json
          sudo ls -la /var/_pandora/kvrocks/src/kvrocks /var/_pandora/valkey/src/valkey-server || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - logs
        run: |
          set -x
          sudo tail -200 /var/log/syslog
          sudo grep oom /var/log/syslog
          sudo tail -200 /var/_pandora/pandora/logs/warning.log
          journalctl -xe -l --no-pager | grep -iE "pandora.*error"
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - misc
        run: |
          set -x
          sudo find /var/_pandora/.cache/pypoetry/ /usr -iname 'uno.py' -ls || true
          sudo find /var/_pandora/.cache/pypoetry/ /usr -iname 'unohelper.py' -ls || true
          sudo ls -la /var/lib/clamav/ || true
          sudo ls -la /var/run/clamav/clamd.ctl || true
          ls -la /etc/apparmor.d/usr.lib.libreoffice* || true
          sudo cat /etc/apparmor.d/usr.lib.libreoffice.program.soffice.bin || true
          sudo ls -l /tmp/apparmor-bugreport-*.txt || true
          sudo cat /tmp/apparmor-bugreport-*.txt || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - poetry
        run: |
          /usr/local/share/poetry/bin/poetry install --dry-run --sync --no-ansi
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - curl
        run: |
          curl -vL http://localhost:6100
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - apparmor
        run: |
          set -x
          sudo grep -r "runbindable*/*" /etc/apparmor.d
          sudo ls -l /etc/apparmor.d/usr.lib.libreoffice*
          sudo cat /etc/apparmor.d/usr.lib.libreoffice*
          dpkg -l | grep apparmor
        if: ${{ always() }}
        continue-on-error: true
